// Next.js의 메타데이터 타입을 가져옵니다 (SEO, 페이지 제목 등)
import type { Metadata } from 'next';
// Google Fonts에서 폰트를 가져옵니다
import { Geist, Geist_Mono } from 'next/font/google';
// 전역 CSS 스타일을 가져옵니다 (Tailwind CSS 설정 포함)
import './globals.css';
// 전역 상태 관리자들을 가져옵니다 (인증, 테마, 쿼리 클라이언트 등)
import Providers from './providers';

// Geist Sans 폰트 설정 (메인 텍스트용)
const geistSans = Geist({
  variable: '--font-geist-sans', // CSS 변수명 설정
  subsets: ['latin'], // 라틴 문자만 포함 (성능 최적화)
});

// Geist Mono 폰트 설정 (코드, 숫자용)
const geistMono = Geist_Mono({
  variable: '--font-geist-mono', // CSS 변수명 설정
  subsets: ['latin'], // 라틴 문자만 포함
});

// 페이지 메타데이터 설정 (SEO, 브라우저 탭 제목 등)
export const metadata: Metadata = {
  title: 'Create Next App', // 브라우저 탭에 표시될 제목
  description: 'Generated by create next app', // 검색엔진용 설명
};

// 루트 레이아웃 컴포넌트 - 모든 페이지의 기본 구조를 정의
export default function RootLayout({
  children, // 각 페이지의 내용이 여기에 들어갑니다
}: Readonly<{
  children: React.ReactNode; // TypeScript 타입 정의
}>) {
  return (
    // HTML 태그 - suppressHydrationWarning으로 서버/클라이언트 불일치 경고 억제
    <html suppressHydrationWarning>
      {/* body 태그 - 폰트 변수들을 CSS 클래스로 적용 */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Providers로 감싸서 전역 상태 관리자들을 모든 컴포넌트에서 사용할 수 있게 함 */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
